# Site settings
title: EnoughMind
email: jmartgod@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Psicología, Recursos Humanos y Análisis de datos.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://enoughmind.github.io" # the base hostname & protocol for your site
twitter_username: godenoughfor
github_username:  godenoughfor

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty

author:
    name: 'godenoughfor'
    url: https://twitter.com/godenoughfor

paginate: 10


