# Site wide configuration

title: EnoughMind
description: "Tecnología, psicología y datos."
logo: site-logo.jpg# 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: es
url: http://localhost:4000

# Jekyll configuration

sass:
    sass_dir: _sass
    style: expanded
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: José Godoy
  email: jmartgod@enoughmind.com
  twitter: godenoughfor
  google:
    ad-client: 
    ad-slot: 
  bio: Un psicometra en potencia.
  avatar: bio-photo.jpg# 160x160 px image for author byline
disqus-shortname: godenoughfor


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
